apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
    env: production
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: frontend-pod